### ISSUE TITLE
Release version that supports TF 0.13

### ISSUE THREAD

**Issue by chrisgilmerproj** [trussworks/terraform-aws-mfa#43]
Hi folks! I noticed that version 2.1.1 is available on the terraform registry with the version pinned to TF 0.12. You've updated the code recently so could I ask you to release a new version to the registry?

**Comment by chrisgilmerproj** [comment]
@eeeady - one more that needs an updated release if you have a chance 😄

**Comment by davidski** [comment]
tf 0.14 is now GA. Any chance this update could be pushed in the near future? 🙏

**Comment by chrisgilmerproj** [comment]
@dynamike - could you help out with updating this module please?

**Comment by eeeady** [comment]
Sorry we missed this!!! Just released v3.0.0 with this support.

**Comment by chrisgilmerproj** [comment]
Thanks! Really appreciate it.
